### ISSUE TITLE
Using MPI_fence and MPI_put

### ISSUE THREAD

**Issue by luispaulomr** [spcl/CLaMPI#1]
My code does some calls to MPI_Fence and MPI_Put, and the compiler output states that the window I passed as a parameter is not a MPI_Win type (it's of type CMPI_Win).

Do you know what would be the best way to circumvent this?

**Comment by SalvatoreDiGirolamo** [comment]
Yes, you can get the original MPI window from a CMPI_Win `x` by accessing `x.win`. 
Here is the CMPI_Win definition:

https://github.com/SalvatoreDiGirolamo/CLaMPI/blob/20391970affd690b3ab7faed0212462cda2b1bec/src/clampi.h#L49-L59

**Comment by luispaulomr** [comment]
Ok, I see. Thanks.
